# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_section_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_Section_Window(object):
    def setupUi(self, Add_Section_Window):
        Add_Section_Window.setObjectName("Add_Section_Window")
        Add_Section_Window.resize(537, 300)
        self.centralwidget = QtWidgets.QWidget(Add_Section_Window)
        self.centralwidget.setStyleSheet("background-color: white; \n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: black; ")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: black;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignLeft)
        self.section_name_add = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.section_name_add.sizePolicy().hasHeightForWidth())
        self.section_name_add.setSizePolicy(sizePolicy)
        self.section_name_add.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.section_name_add.setFont(font)
        self.section_name_add.setStyleSheet("color: black;")
        self.section_name_add.setObjectName("section_name_add")
        self.horizontalLayout_3.addWidget(self.section_name_add, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.section_add_form_button = QtWidgets.QPushButton(self.frame_4)
        self.section_add_form_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.section_add_form_button.sizePolicy().hasHeightForWidth())
        self.section_add_form_button.setSizePolicy(sizePolicy)
        self.section_add_form_button.setMinimumSize(QtCore.QSize(0, 35))
        self.section_add_form_button.setMaximumSize(QtCore.QSize(170, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.section_add_form_button.setFont(font)
        self.section_add_form_button.setStyleSheet(":enabled {\n"
"   color: #fff;\n"
"  background-color: #5cb85c;\n"
"  border-color: #4cae4c;\n"
"}\n"
":hover {\n"
"    color: #fff;\n"
"  background-color: #449d44;\n"
"  border-color: #255625;\n"
"}\n"
"\n"
":focus\n"
"{\n"
"color: #fff;\n"
"  background-color: #449d44;\n"
"  border-color: #398439;\n"
"}\n"
"\n"
":disabled\n"
"{\n"
"  color: #fff;\n"
"  background-color: rgba(92, 184, 92, 175);\n"
"  border-color: #4cae4c;\n"
"}")
        self.section_add_form_button.setObjectName("section_add_form_button")
        self.horizontalLayout_4.addWidget(self.section_add_form_button)
        self.verticalLayout.addWidget(self.frame_4)
        Add_Section_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Add_Section_Window)
        QtCore.QMetaObject.connectSlotsByName(Add_Section_Window)

    def retranslateUi(self, Add_Section_Window):
        _translate = QtCore.QCoreApplication.translate
        Add_Section_Window.setWindowTitle(_translate("Add_Section_Window", "MainWindow"))
        self.label.setText(_translate("Add_Section_Window", "Add Section"))
        self.label_3.setText(_translate("Add_Section_Window", "Section Name"))
        self.section_add_form_button.setText(_translate("Add_Section_Window", "Add Section"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Add_Section_Window = QtWidgets.QMainWindow()
    ui = Ui_Add_Section_Window()
    ui.setupUi(Add_Section_Window)
    Add_Section_Window.show()
    sys.exit(app.exec_())
