# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_slot_preferences.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QGraphicsOpacityEffect



class Ui_Add_Slot_PReferences_Teacher_Window(object):
    def setupUi(self, Add_Slot_PReferences_Teacher_Window):
        Add_Slot_PReferences_Teacher_Window.setObjectName("Add_Slot_PReferences_Teacher_Window")
        Add_Slot_PReferences_Teacher_Window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Add_Slot_PReferences_Teacher_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(13, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.slot_preference_teacher_name = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.slot_preference_teacher_name.setFont(font)
        self.slot_preference_teacher_name.setObjectName("slot_preference_teacher_name")
        self.horizontalLayout_2.addWidget(self.slot_preference_teacher_name)
        self.updation_message_label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.updation_message_label.setFont(font)
        self.updation_message_label.setStyleSheet("color: white;\n"
"background-color: rgb(24, 184, 0);")
        self.updation_message_label.setObjectName("updation_message_label")
        self.horizontalLayout_2.addWidget(self.updation_message_label, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.slot_preference_table = QtWidgets.QTableWidget(self.frame_3)
        self.slot_preference_table.setObjectName("slot_preference_table")
        self.slot_preference_table.setColumnCount(5)
        self.slot_preference_table.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.slot_preference_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.slot_preference_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.slot_preference_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.slot_preference_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.slot_preference_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.slot_preference_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.slot_preference_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.slot_preference_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.slot_preference_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.slot_preference_table.setHorizontalHeaderItem(4, item)
        self.horizontalLayout_4.addWidget(self.slot_preference_table)
        self.verticalLayout.addWidget(self.frame_3)
        Add_Slot_PReferences_Teacher_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Add_Slot_PReferences_Teacher_Window)
        QtCore.QMetaObject.connectSlotsByName(Add_Slot_PReferences_Teacher_Window)

        self.updation_message_label.hide()

        self.slot_preference_table.horizontalHeader().setStretchLastSection(True)
        self.slot_preference_table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.slot_preference_table.verticalHeader().setStretchLastSection(True)
        self.slot_preference_table.verticalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        try:
            self.DB = mc.connect(host="localhost", user="root", password="", database="timetable_manager")
        except mc.Error as e:
            print("Error")

    def launch_window(self, teacher_id):
        mycursor = self.DB.cursor()
        for row in range(0, 5):
            for col in range(0, 5):
                
                query = "select * from junc_slot_preferences where teacher_id = %s and day_id = %s and slot_id = %s"
                val = (int(teacher_id), int(row+1), int(col+1))
                mycursor.execute(query, val)
                mycursor.fetchall()
                if (mycursor.rowcount == 0):
                    self.slot_preference_table.setItem(row, col, QtWidgets.QTableWidgetItem(str("Available")))
                    self.slot_preference_table.item(row, col).setBackground(QtGui.QColor(92, 184, 92))
                else:
                    self.slot_preference_table.setItem(row, col, QtWidgets.QTableWidgetItem(str("Not Available")))
                    self.slot_preference_table.item(row, col).setBackground(QtGui.QColor(217, 83, 79))

    def fade(self, widget):
        self.effect = QGraphicsOpacityEffect()
        widget.setGraphicsEffect(self.effect)

        self.animation = QtCore.QPropertyAnimation(self.effect, b"opacity")
        self.animation.setDuration(1000)
        self.animation.setStartValue(1)
        self.animation.setEndValue(0)
        self.animation.start()

    def retranslateUi(self, Add_Slot_PReferences_Teacher_Window):
        _translate = QtCore.QCoreApplication.translate
        Add_Slot_PReferences_Teacher_Window.setWindowTitle(_translate("Add_Slot_PReferences_Teacher_Window", "MainWindow"))
        self.label.setText(_translate("Add_Slot_PReferences_Teacher_Window", "Slot Preferences"))
        self.slot_preference_teacher_name.setText(_translate("Add_Slot_PReferences_Teacher_Window", "Teacher Name"))
        self.updation_message_label.setText(_translate("Add_Slot_PReferences_Teacher_Window", "Updated Successfully."))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        item = self.slot_preference_table.verticalHeaderItem(0)
        item.setFont(font)
        item.setText(_translate("Add_Slot_PReferences_Teacher_Window", "Mon"))
        item = self.slot_preference_table.verticalHeaderItem(1)
        item.setFont(font)
        item.setText(_translate("Add_Slot_PReferences_Teacher_Window", "Tue"))
        item = self.slot_preference_table.verticalHeaderItem(2)
        item.setFont(font)
        item.setText(_translate("Add_Slot_PReferences_Teacher_Window", "Wed"))
        item = self.slot_preference_table.verticalHeaderItem(3)
        item.setFont(font)
        item.setText(_translate("Add_Slot_PReferences_Teacher_Window", "Thur"))
        item = self.slot_preference_table.verticalHeaderItem(4)
        item.setFont(font)
        item.setText(_translate("Add_Slot_PReferences_Teacher_Window", "Fri"))
        item = self.slot_preference_table.horizontalHeaderItem(0)
        item.setFont(font)
        item.setText(_translate("Add_Slot_PReferences_Teacher_Window", "1st Slot"))
        item = self.slot_preference_table.horizontalHeaderItem(1)
        item.setFont(font)
        item.setText(_translate("Add_Slot_PReferences_Teacher_Window", "2nd Slot"))
        item = self.slot_preference_table.horizontalHeaderItem(2)
        item.setFont(font)
        item.setText(_translate("Add_Slot_PReferences_Teacher_Window", "3rd Slot"))
        item = self.slot_preference_table.horizontalHeaderItem(3)
        item.setFont(font)
        item.setText(_translate("Add_Slot_PReferences_Teacher_Window", "4th Slot"))
        item = self.slot_preference_table.horizontalHeaderItem(4)
        item.setFont(font)
        item.setText(_translate("Add_Slot_PReferences_Teacher_Window", "5th Slot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Add_Slot_PReferences_Teacher_Window = QtWidgets.QMainWindow()
    ui = Ui_Add_Slot_PReferences_Teacher_Window()
    ui.setupUi(Add_Slot_PReferences_Teacher_Window)
    Add_Slot_PReferences_Teacher_Window.show()
    sys.exit(app.exec_())
