# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registered_section_student_details.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registered_Section_Students_Window(object):
    def setupUi(self, Registered_Section_Students_Window):
        Registered_Section_Students_Window.setObjectName("Registered_Section_Students_Window")
        Registered_Section_Students_Window.resize(800, 600)
        Registered_Section_Students_Window.setStyleSheet("* {\n"
"border: none;\n"
"background-color: white;\n"
"}\n"
"\n"
".QTableWidget\n"
"{\n"
"alternate-background-color: rgb(241, 241, 241);\n"
"background-color: white;\n"
"}\n"
"\n"
".QTableWidget:item\n"
"{\n"
"color: black;\n"
"padding: 5px;\n"
"}\n"
"\n"
".QHeaderView::section\n"
"{\n"
"background-color: white;\n"
"color: black;\n"
"font-weight: bold;\n"
"border: 0px;\n"
"border-bottom: 1px solid;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Registered_Section_Students_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("margin: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.registered_section_course_name = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.registered_section_course_name.setFont(font)
        self.registered_section_course_name.setObjectName("registered_section_course_name")
        self.horizontalLayout_2.addWidget(self.registered_section_course_name, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignTop)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.registered_section_section_name = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.registered_section_section_name.setFont(font)
        self.registered_section_section_name.setObjectName("registered_section_section_name")
        self.horizontalLayout_3.addWidget(self.registered_section_section_name, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignTop)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.registered_section_teacher_name = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.registered_section_teacher_name.setFont(font)
        self.registered_section_teacher_name.setObjectName("registered_section_teacher_name")
        self.horizontalLayout_4.addWidget(self.registered_section_teacher_name, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.frame_6, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.add_registered_section_student = QtWidgets.QPushButton(self.frame_7)
        self.add_registered_section_student.setStyleSheet("QPushButton\n"
"{\n"
" display: inline-block;\n"
"  padding: 6px 12px;\n"
"  margin-bottom: 0;\n"
"  font-size: 14px;\n"
"  font-weight: normal;\n"
"  line-height: 1.42857143;\n"
"  text-align: center;\n"
"  white-space: nowrap;\n"
"  vertical-align: middle;\n"
"  -ms-touch-action: manipulation;\n"
"      touch-action: manipulation;\n"
"  cursor: pointer;\n"
"  -webkit-user-select: none;\n"
"     -moz-user-select: none;\n"
"      -ms-user-select: none;\n"
"          user-select: none;\n"
"  background-image: none;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 4px;\n"
"color: #fff; \n"
"background-color: #5cb85c;\n"
"  border-color: #4cae4c;\n"
"}\n"
"\n"
"\n"
":hover\n"
"{\n"
" color: #fff;\n"
"  background-color: #449d44;\n"
"  border-color: #398439;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-add-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_registered_section_student.setIcon(icon)
        self.add_registered_section_student.setIconSize(QtCore.QSize(24, 24))
        self.add_registered_section_student.setObjectName("add_registered_section_student")
        self.horizontalLayout_6.addWidget(self.add_registered_section_student)
        self.delete_all_registered_section_student = QtWidgets.QPushButton(self.frame_7)
        self.delete_all_registered_section_student.setStyleSheet("QPushButton\n"
"{\n"
" display: inline-block;\n"
"  padding: 6px 12px;\n"
"  margin-bottom: 0;\n"
"  font-size: 14px;\n"
"  font-weight: normal;\n"
"  line-height: 1.42857143;\n"
"  text-align: center;\n"
"  white-space: nowrap;\n"
"  vertical-align: middle;\n"
"  -ms-touch-action: manipulation;\n"
"      touch-action: manipulation;\n"
"  cursor: pointer;\n"
"  -webkit-user-select: none;\n"
"     -moz-user-select: none;\n"
"      -ms-user-select: none;\n"
"          user-select: none;\n"
"  background-image: none;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 4px;\n"
"color: #fff; \n"
"background-color: #5cb85c;\n"
"  border-color: #4cae4c;\n"
"}\n"
"QPushButton\n"
"{\n"
"color: #fff;\n"
"  background-color: #d9534f;\n"
"  border-color: #d43f3a;\n"
"\n"
"}\n"
"\n"
"\n"
":hover\n"
"{\n"
" color: #fff;\n"
"  background-color: #c9302c;\n"
"  border-color: #ac2925;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/delete_icon_red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_all_registered_section_student.setIcon(icon1)
        self.delete_all_registered_section_student.setIconSize(QtCore.QSize(24, 24))
        self.delete_all_registered_section_student.setObjectName("delete_all_registered_section_student")
        self.horizontalLayout_6.addWidget(self.delete_all_registered_section_student)
        self.horizontalLayout_5.addWidget(self.frame_7, 0, QtCore.Qt.AlignTop)
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.registered_section_student_search_text = QtWidgets.QLineEdit(self.frame_8)
        self.registered_section_student_search_text.setStyleSheet("margin-left: 25px;\n"
"border-bottom: 1px solid;\n"
"")
        self.registered_section_student_search_text.setObjectName("registered_section_student_search_text")
        self.horizontalLayout_7.addWidget(self.registered_section_student_search_text)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-search-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_7.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        self.horizontalLayout_5.addWidget(self.frame_8, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.registered_section_student_table = QtWidgets.QTableWidget(self.frame_3)
        self.registered_section_student_table.setStyleSheet("background-color: white; ")
        self.registered_section_student_table.setObjectName("registered_section_student_table")
        self.registered_section_student_table.setColumnCount(4)
        self.registered_section_student_table.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.registered_section_student_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registered_section_student_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.registered_section_student_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registered_section_student_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.registered_section_student_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.registered_section_student_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.registered_section_student_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registered_section_student_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.registered_section_student_table.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.registered_section_student_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registered_section_student_table.setItem(1, 2, item)
        self.horizontalLayout_8.addWidget(self.registered_section_student_table)
        self.verticalLayout.addWidget(self.frame_3)
        Registered_Section_Students_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Registered_Section_Students_Window)
        QtCore.QMetaObject.connectSlotsByName(Registered_Section_Students_Window)

    def retranslateUi(self, Registered_Section_Students_Window):
        _translate = QtCore.QCoreApplication.translate
        Registered_Section_Students_Window.setWindowTitle(_translate("Registered_Section_Students_Window", "MainWindow"))
        self.registered_section_course_name.setText(_translate("Registered_Section_Students_Window", "Course Name"))
        self.registered_section_section_name.setText(_translate("Registered_Section_Students_Window", "Section"))
        self.registered_section_teacher_name.setText(_translate("Registered_Section_Students_Window", "Teacher"))
        self.add_registered_section_student.setText(_translate("Registered_Section_Students_Window", "Add New"))
        self.delete_all_registered_section_student.setText(_translate("Registered_Section_Students_Window", "Delete All"))
        item = self.registered_section_student_table.verticalHeaderItem(0)
        item.setText(_translate("Registered_Section_Students_Window", "1"))
        item = self.registered_section_student_table.verticalHeaderItem(1)
        item.setText(_translate("Registered_Section_Students_Window", "2"))
        item = self.registered_section_student_table.horizontalHeaderItem(0)
        item.setText(_translate("Registered_Section_Students_Window", "ID"))
        item = self.registered_section_student_table.horizontalHeaderItem(1)
        item.setText(_translate("Registered_Section_Students_Window", "ID"))
        item = self.registered_section_student_table.horizontalHeaderItem(2)
        item.setText(_translate("Registered_Section_Students_Window", "Roll Number"))
        item = self.registered_section_student_table.horizontalHeaderItem(3)
        item.setText(_translate("Registered_Section_Students_Window", "Actions"))
        __sortingEnabled = self.registered_section_student_table.isSortingEnabled()
        self.registered_section_student_table.setSortingEnabled(False)
        item = self.registered_section_student_table.item(0, 0)
        item.setText(_translate("Registered_Section_Students_Window", "Hassan"))
        item = self.registered_section_student_table.item(0, 2)
        item.setText(_translate("Registered_Section_Students_Window", "1111"))
        item = self.registered_section_student_table.item(1, 0)
        item.setText(_translate("Registered_Section_Students_Window", "Ashas"))
        item = self.registered_section_student_table.item(1, 2)
        item.setText(_translate("Registered_Section_Students_Window", "231"))
        self.registered_section_student_table.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Registered_Section_Students_Window = QtWidgets.QMainWindow()
    ui = Ui_Registered_Section_Students_Window()
    ui.setupUi(Registered_Section_Students_Window)
    Registered_Section_Students_Window.show()
    sys.exit(app.exec_())
